project_id = "bsfwuueujkhptnfifyef"

[functions.generate-assessment]
verify_jwt = false

[functions.regenerate-question]
verify_jwt = false

[functions.parse-paper]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false
