/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as NewRouteImport } from './routes/new'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BankRouteImport } from './routes/bank'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaperSetNewRouteImport } from './routes/paper-set.new'
import { Route as PaperSetIdRouteImport } from './routes/paper-set.$id'
import { Route as AssessmentIdRouteImport } from './routes/assessment.$id'
import { Route as AdminSyllabusIndexRouteImport } from './routes/admin.syllabus.index'
import { Route as AdminSyllabusIdRouteImport } from './routes/admin.syllabus.$id'

const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperSetNewRoute = PaperSetNewRouteImport.update({
  id: '/paper-set/new',
  path: '/paper-set/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperSetIdRoute = PaperSetIdRouteImport.update({
  id: '/paper-set/$id',
  path: '/paper-set/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIdRoute = AssessmentIdRouteImport.update({
  id: '/assessment/$id',
  path: '/assessment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSyllabusIndexRoute = AdminSyllabusIndexRouteImport.update({
  id: '/admin/syllabus/',
  path: '/admin/syllabus/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSyllabusIdRoute = AdminSyllabusIdRouteImport.update({
  id: '/admin/syllabus/$id',
  path: '/admin/syllabus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank': typeof BankRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/our-story': typeof OurStoryRoute
  '/papers': typeof PapersRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/paper-set/$id': typeof PaperSetIdRoute
  '/paper-set/new': typeof PaperSetNewRoute
  '/admin/syllabus/$id': typeof AdminSyllabusIdRoute
  '/admin/syllabus/': typeof AdminSyllabusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank': typeof BankRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/our-story': typeof OurStoryRoute
  '/papers': typeof PapersRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/paper-set/$id': typeof PaperSetIdRoute
  '/paper-set/new': typeof PaperSetNewRoute
  '/admin/syllabus/$id': typeof AdminSyllabusIdRoute
  '/admin/syllabus': typeof AdminSyllabusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank': typeof BankRoute
  '/dashboard': typeof DashboardRoute
  '/new': typeof NewRoute
  '/our-story': typeof OurStoryRoute
  '/papers': typeof PapersRoute
  '/assessment/$id': typeof AssessmentIdRoute
  '/paper-set/$id': typeof PaperSetIdRoute
  '/paper-set/new': typeof PaperSetNewRoute
  '/admin/syllabus/$id': typeof AdminSyllabusIdRoute
  '/admin/syllabus/': typeof AdminSyllabusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bank'
    | '/dashboard'
    | '/new'
    | '/our-story'
    | '/papers'
    | '/assessment/$id'
    | '/paper-set/$id'
    | '/paper-set/new'
    | '/admin/syllabus/$id'
    | '/admin/syllabus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bank'
    | '/dashboard'
    | '/new'
    | '/our-story'
    | '/papers'
    | '/assessment/$id'
    | '/paper-set/$id'
    | '/paper-set/new'
    | '/admin/syllabus/$id'
    | '/admin/syllabus'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bank'
    | '/dashboard'
    | '/new'
    | '/our-story'
    | '/papers'
    | '/assessment/$id'
    | '/paper-set/$id'
    | '/paper-set/new'
    | '/admin/syllabus/$id'
    | '/admin/syllabus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BankRoute: typeof BankRoute
  DashboardRoute: typeof DashboardRoute
  NewRoute: typeof NewRoute
  OurStoryRoute: typeof OurStoryRoute
  PapersRoute: typeof PapersRoute
  AssessmentIdRoute: typeof AssessmentIdRoute
  PaperSetIdRoute: typeof PaperSetIdRoute
  PaperSetNewRoute: typeof PaperSetNewRoute
  AdminSyllabusIdRoute: typeof AdminSyllabusIdRoute
  AdminSyllabusIndexRoute: typeof AdminSyllabusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-set/new': {
      id: '/paper-set/new'
      path: '/paper-set/new'
      fullPath: '/paper-set/new'
      preLoaderRoute: typeof PaperSetNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-set/$id': {
      id: '/paper-set/$id'
      path: '/paper-set/$id'
      fullPath: '/paper-set/$id'
      preLoaderRoute: typeof PaperSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$id': {
      id: '/assessment/$id'
      path: '/assessment/$id'
      fullPath: '/assessment/$id'
      preLoaderRoute: typeof AssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/syllabus/': {
      id: '/admin/syllabus/'
      path: '/admin/syllabus'
      fullPath: '/admin/syllabus/'
      preLoaderRoute: typeof AdminSyllabusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/syllabus/$id': {
      id: '/admin/syllabus/$id'
      path: '/admin/syllabus/$id'
      fullPath: '/admin/syllabus/$id'
      preLoaderRoute: typeof AdminSyllabusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BankRoute: BankRoute,
  DashboardRoute: DashboardRoute,
  NewRoute: NewRoute,
  OurStoryRoute: OurStoryRoute,
  PapersRoute: PapersRoute,
  AssessmentIdRoute: AssessmentIdRoute,
  PaperSetIdRoute: PaperSetIdRoute,
  PaperSetNewRoute: PaperSetNewRoute,
  AdminSyllabusIdRoute: AdminSyllabusIdRoute,
  AdminSyllabusIndexRoute: AdminSyllabusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
